### ISSUE TITLE
[Bug] Updating to Overwolf deletes previous instances

### ISSUE THREAD

**Issue by typeomi** [FTBTeam/FTB-App-Overwolf#20] opened 2020-12-03 22:04 UTC
**App Version:**
App: 202012021741-eaf41def11-debugging

**UI Version:**
UI: 9e6200dd

**Log Files:**
https://pste.ch/rikakatija

**Describe the bug**
Updating the FTB App to the most recent version, which introduces the Overwolf version of the launcher, deletes all previous modpack instances from the FTB App files.

**To Reproduce**
1. Launch any previous version of the FTB App
2. Update FTB App
3. Launch app after updating

**Expected behavior**
Updating the app should not delete files to be used in the launcher.

**Comment by Corrbo** [comment] 2020-12-19 05:06
This happened to me too, I lost a world with hundreds of hours on it

**Comment by MichaelHillcox** [comment] 2021-08-10 12:35
Hmm, the migration of this should have migrated this data over, your data will still be on your system but in the old location. I'm gunna close this as the issue is quite old but if you want more help, just comment back :+1:

**Closed by MichaelHillcox** 2021-08-10 12:35 UTC
